
[functions.rank_and_filter_posts]
enabled = true
verify_jwt = true
import_map = "./functions/rank_and_filter_posts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/rank_and_filter_posts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/rank_and_filter_posts/*.html" ]
